language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - tip

services:
  - redis-server

before_install:

install:
 - go get github.com/gin-gonic/gin
 - go get github.com/gomodule/redigo/redis
 - go get github.com/lib/pq
 - go get github.com/dgrijalva/jwt-go

 - go get github.com/northbright/csvhelper
 - go get github.com/northbright/redishelper
 - go get github.com/northbright/pathhelper
 - go get github.com/northbright/jwthelper
 - go get github.com/northbright/uuid

before_script:

script:
  - go test -v ./...

  # Employee
  - cd employee/tools/update-employees/
  - go build
  - ./update-employees -a='127.0.0.1:6379' -p='' -f='files/original.csv'
  - ./update-employees -a='127.0.0.1:6379' -p='' -f='files/update.csv'
  - cd ../../
