language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - tip

services:
  - postgresql

addons:
  postgresql: "9.6"

before_install:

install:
 - go get github.com/gin-gonic/gin
 - go get github.com/gomodule/redigo/redis
 - go get github.com/lib/pq
 - go get github.com/dgrijalva/jwt-go
 - go get github.com/jmoiron/sqlx

 - go get github.com/northbright/csvhelper
 - go get github.com/northbright/redishelper
 - go get github.com/northbright/pathhelper
 - go get github.com/northbright/jwthelper
 - go get github.com/northbright/uuid
 - go get github.com/northbright/validate

before_script:
 - psql -c 'CREATE DATABASE test;' -U postgres

script:
  - go test -v ./...

  # Tools
  - cd tools/create-employees/
  - go build
  - cd ../../
